# Generated by Django 4.2.6 on 2023-10-15 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='cadastro',
        ),
    ]
