# Generated by Django 4.2.6 on 2023-10-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('desc_produto', models.TextField(primary_key=True, serialize=False)),
                ('marca', models.TextField(max_length=255)),
                ('modelo', models.TextField(max_length=255)),
                ('preço', models.IntegerField()),
            ],
        ),
    ]
