# Generated by Django 4.2.6 on 2023-10-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_app', '0003_rename_desc_produto_cadastro_descrição'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='tipo',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='descrição',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='preço',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
