# Generated by Django 4.2.6 on 2023-10-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_app', '0004_cadastro_tipo_alter_cadastro_descrição_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='tipo',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
