# Generated by Django 4.2.6 on 2023-10-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_app', '0005_alter_cadastro_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='tipo',
            field=models.CharField(max_length=255),
        ),
    ]
