# Generated by Django 4.2.6 on 2023-10-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_app', '0007_alter_cadastro_preço_alter_cadastro_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='preço',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
