# Generated by Django 4.2.6 on 2023-10-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_app', '0008_alter_cadastro_preço'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='tipo',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
